kind: Secret
apiVersion: v1
metadata:
  name: aws-connection-mlops-workshop-bucket
  namespace: mlops-workshop
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: mlops-workshop-bucket
    argocd.argoproj.io/sync-wave: "-2"
data:
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_DEFAULT_REGION: ''
  AWS_S3_BUCKET: bWxvcHMtd29ya3Nob3A=
  AWS_S3_ENDPOINT: aHR0cDovL21pbmlvLW1sLXdvcmtzaG9wLm1pbmlvLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbDo5MDAw
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=
type: Opaque

