apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: hands-recognizer
    serving.kserve.io/deploymentMode: ModelMesh
    app.kubernetes.io/instance: mlops-workshop
  labels:
    opendatahub.io/dashboard: "true"
  name: hands-recognizer
  namespace: mlops-workshop
spec:
  predictor:
    model:
      modelFormat:
        name: openvino_ir
        version: opset1
      runtime: mlops-workshop
      storage:
        key: aws-connection-mlops-workshop-bucket
        path: models/model-1.0.0