apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aws-connection-mlops-workshop-bucket.yaml
  - mlops-workshop-storage.yaml
  - notebook.yaml
  - onboarding-data-to-bucket-job.yaml
  - serving-runtime.yaml
  - inference-service.yaml
  - inference-service-route.yaml
  #- data-science-pipeline.yaml
