apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - data-science-cluster.yaml
  - aws-connection-mlops-workshop-bucket.yaml
  - mlops-workshop-storage.yaml
  - notebook.yaml
  #- data-science-pipeline.yaml
  #- inference-service.yaml
