apiVersion: v1
data:
  odh_dsp.json: eyJkaXNwbGF5X25hbWUiOiJEYXRhIFNjaWVuY2UgUGlwZWxpbmUiLCJtZXRhZGF0YSI6eyJ0YWdzIjpbXSwiZGlzcGxheV9uYW1lIjoiRGF0YSBTY2llbmNlIFBpcGVsaW5lIiwiZW5naW5lIjoiQXJnbyIsImF1dGhfdHlwZSI6IktVQkVSTkVURVNfU0VSVklDRV9BQ0NPVU5UX1RPS0VOIiwiYXBpX2VuZHBvaW50IjoiaHR0cHM6Ly9kcy1waXBlbGluZS1kc3BhLW1sb3BzLXdvcmtzaG9wLmFwcHMuY2x1c3Rlci0yOWZ2cS5keW5hbWljLnJlZGhhdHdvcmtzaG9wcy5pbyIsInB1YmxpY19hcGlfZW5kcG9pbnQiOiJodHRwczovL3Job2RzLWRhc2hib2FyZC1yZWRoYXQtb2RzLWFwcGxpY2F0aW9ucy5hcHBzLmNsdXN0ZXItMjlmdnEuZHluYW1pYy5yZWRoYXR3b3Jrc2hvcHMuaW8vcGlwZWxpbmVSdW5zL21sb3BzLXdvcmtzaG9wL3BpcGVsaW5lUnVuL3ZpZXcvIiwiY29zX2F1dGhfdHlwZSI6IktVQkVSTkVURVNfU0VDUkVUIiwiY29zX3NlY3JldCI6ImF3cy1jb25uZWN0aW9uLW1sb3BzLXdvcmtzaG9wLWJ1Y2tldCIsImNvc19lbmRwb2ludCI6Imh0dHA6Ly9taW5pby1tbC13b3Jrc2hvcC5taW5pby1zeXN0ZW0uc3ZjLmNsdXN0ZXIubG9jYWw6OTAwMCIsImNvc19idWNrZXQiOiJtbG9wcy13b3Jrc2hvcCIsImNvc191c2VybmFtZSI6Im1pbmlvIiwiY29zX3Bhc3N3b3JkIjoibWluaW8xMjMiLCJydW50aW1lX3R5cGUiOiJLVUJFRkxPV19QSVBFTElORVMifSwic2NoZW1hX25hbWUiOiJrZnAifQ==
kind: Secret
metadata:
  name: ds-pipeline-config
  namespace: mlops-workshop
  annotations:
    argocd.argoproj.io/sync-wave: "3"
type: Opaque