---
apiVersion: batch/v1
kind: Job
metadata:
  name: onboarding-clone-repository
  namespace: mlops-workshop
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccount: onboarding
      initContainers:
      - name: wait-for-workbench
        image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args:
        - -ec
        - |-
          echo -n "Waiting for workbench pod in mlops-workshop namespace"
          while [ -z "\$(oc get pods -n mlops-workshop -l app=hands-recognizer -o custom-columns=STATUS:.status.phase --no-headers | grep Running 2>/dev/null)" ]; do
              echo -n '.'
              sleep 1
          done
          echo -n "Workbench pod is running in mlops-workshop namespace"
      containers:
      - name: git-clone
        image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:1.2
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args:
        - -ec
        - |-
          pod_name=$(oc get pods -n mlops-workshop --selector=app=hands-recognizer -o jsonpath='{.items[0].metadata.name}')
          oc exec $pod_name -- sh -c "rm -rf mlops-workshop && git clone https://github.com/JuanmaBM/mlops-workshop"
      restartPolicy: Never