apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  annotations:
    app.kubernetes.io/name: datasciencecluster
    argocd.argoproj.io/sync-wave: "5"
  name: default-dsc
spec:
  components:
    codeflare:
      managementState: Removed
    dashboard:
      managementState: Managed
    datasciencepipelines:
      managementState: Managed
    kserve:
      managementState: Removed
    kueue:
      managementState: Removed
    modelmeshserving:
      managementState: Managed
    ray:
      managementState: Removed
    workbenches:
      managementState: Managed
