apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhods-operator
  namespace: redhat-ods-operator
spec:
  channel: stable-2.8
  name: rhods-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

