apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: minio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/minio
    repoURL: https://github.com/JuanmaBM/mlops-workshop.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
