apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-workshop
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: mlops-workshop
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/rhai-workbench
    repoURL: https://github.com/JuanmaBM/mlops-workshop.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
